version: '3.8'

services:
  text-generation:
    image: ghcr.io/huggingface/text-generation-inference:0.9
    hostname: 0.0.0.0
    environment:
      - HF_API_TOKEN=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
      - HF_HUB_ENABLE_HF_TRANSFER=false
    volumes:
      - ~/.cache/huggingface/hub:/data
    ports:
      - "8080:80"
    ipc: host
    command: >
      --model-id meta-llama/Llama-2-13b-chat-hf
      --quantize bitsandbytes
      --num-shard 4

#   db:
#     image: ankane/pgvector:latest
#     environment:
#       POSTGRES_DB: mydatabase
#       POSTGRES_USER: myuser
#       POSTGRES_PASSWORD: mypassword
#     volumes:
#       - pgdata2:/var/lib/postgresql/data
#     ports:
#       - "5433:5432"

# volumes:
#   pgdata2: